### ISSUE TITLE
JSON format for perfdata could be simplified

### ISSUE THREAD

**Issue by haxtibal** [Icinga/icinga-powershell-apichecks#5]
JSON response form the `/v1/checker?command=foo` contains a `perfdata` attribute that's a bit nasty to deserialize in statically typed languages, because its type varies:
- a check with one performance data output results in `{"perfdata": "'bar'=3.1415;; "}`, i.e. _string_
- a check with multiple performance data outputs results in `{"perfdata": "perfdata":["'bar'=3.1415;; ", "'baz'=42;; "]}`, i.e. _array of strings_
- a check with no performance data output results in `{"perfdata": {}}`, i.e. _empty object_

The more idiomatic representation would be to just use an array for all cases. It can have no, one, or multiple entries. That's sufficient for all cases, and would work out of the box with common JSON deserializers.

icinga-powershell-apichecks is still young, maybe you could change representation now without breaking too much applications?

**Comment by LordHepipud** [comment]
Yes you are correct, it should always return an array no matter what the output is. We will have to enforce array on `empty` or 1 value arrays, as PowerShell sometimes translates an array with one entry to string instead of an array.

This will ensure you always can count on having an array as return object instead of "lets see what mood I'm in today" :D
